name: Run Tests and upload code coverage

on: [push, pull_request]

jobs:

  run-tests:

    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Run tests and write coverprofile
      shell: bash
      run: |
        go test -race -coverprofile=profile.out -covermode=atomic ./...

    - name: Upload testcoverage to codecov.io
      if: matrix.platform == 'ubuntu-latest' && matrix.go-version == '1.16.x'
      uses: codecov/codecov-action@v1
      with:
        file: ./profile.out
        fail_ci_if_error: true
